### ISSUE TITLE
not overriding icon theme

### ISSUE THREAD

**Issue by kale1d0code** [davidhewitt/shebang-language-associator#2]
Hi thanks for the extension.

I'm trying to get this extension to override an icon that is set by an icon theme with no joy.
also when I set an icon in my settings.json, this extension doesn't override that either

**Comment by davidhewitt** [comment]
Thanks for the question.

Unfortunately this extension can only set the language mode in the editor panel. If you want to control the file icon in the Explorer panel, you will have to use VSCode's builtin `files.associations` setting.
