### ISSUE TITLE
Shebabng not start with '#!'

### ISSUE THREAD

**Issue by cgjosephlee** [davidhewitt/shebang-language-associator#5]
Shebang of zsh completion files starts with `#compdef` which is not recognized.
https://github.com/davidhewitt/shebang-language-associator/blob/27492a949540388fb2fc388e3915c1239abacb6b/src/extension.ts#L53-L55

**Comment by davidhewitt** [comment]
I'd be willing to accept a PR to support this, if you want to add this feature 👍

**Comment by cgjosephlee** [comment]
I know nothing about typescript, but I guess it a simple change of `#! -> #`.
